# Lunar Konstruksi - Remove Full CMS / Return to Classic Admin
# Removes user-facing Full CMS workspace and CMS editing APIs while keeping classic CRUD modules intact.
# Run from repo root:
# powershell -ExecutionPolicy Bypass -File .\Apply_Lunar_Remove_Full_CMS_Classic_Admin.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Phase([string]$Message) {
  Write-Host "[CLASSIC ADMIN] $Message" -ForegroundColor Cyan
}

function Fail([string]$Message) {
  Write-Host ""
  Write-Host "[CLASSIC ADMIN] GAGAL: $Message" -ForegroundColor Red
  exit 1
}

function Write-Utf8NoBom([string]$Path, [string]$Content) {
  $parent = Split-Path -Parent $Path
  if ($parent -and -not (Test-Path -LiteralPath $parent)) {
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
  }
  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $encoding)
}

$repoRoot = (& git rev-parse --show-toplevel 2>$null)
if (-not $repoRoot) {
  Fail "Jalankan script ini dari repository Git Lunar Konstruksi."
}

$repoRoot = $repoRoot.Trim()
Set-Location $repoRoot

$branch = (& git branch --show-current).Trim()
$head = (& git rev-parse --short HEAD).Trim()
Phase "Repo   : $repoRoot"
Phase "Branch : $branch"
Phase "HEAD   : $head"

$trackedStatus = & git status --porcelain --untracked-files=no
if ($LASTEXITCODE -ne 0) {
  Fail "Tidak bisa membaca git status."
}

if ($trackedStatus) {
  Write-Host $trackedStatus
  Fail "Ada perubahan TRACKED yang belum disimpan. Commit/stash dulu agar rollback CMS aman."
}

$required = @(
  "components/admin/sidebar.tsx",
  "app/admin/(dashboard)",
  "features/projects",
  "features/services",
  "features/team",
  "features/testimonials",
  "features/faqs"
)

$missing = @($required | Where-Object { -not (Test-Path -LiteralPath $_) })
if ($missing.Count -gt 0) {
  Write-Host "[CLASSIC ADMIN] Struktur utama yang tidak ditemukan:" -ForegroundColor Yellow
  $missing | ForEach-Object { Write-Host "  - $_" }
  Fail "Repository tidak cocok dengan hasil refactor Lunar yang diharapkan."
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backupRoot = Join-Path $repoRoot ".lunar-backups/remove-cms-$stamp"
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null
Phase "Backup: $backupRoot"

$backupTargets = @(
  "components/admin/sidebar.tsx",
  "app/admin/(dashboard)/cms",
  "components/admin/cms",
  "app/api/admin/cms",
  "ADMIN_CMS_UI.md",
  "CMS_FOUNDATION.md",
  "CMS_MODULES.md",
  "CMS_SEED_GUIDE.md"
)

foreach ($target in $backupTargets) {
  if (-not (Test-Path -LiteralPath $target)) { continue }

  $source = Join-Path $repoRoot $target
  $destination = Join-Path $backupRoot $target
  $destinationParent = Split-Path -Parent $destination
  if ($destinationParent -and -not (Test-Path -LiteralPath $destinationParent)) {
    New-Item -ItemType Directory -Force -Path $destinationParent | Out-Null
  }

  if ((Get-Item -LiteralPath $source).PSIsContainer) {
    Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
  } else {
    Copy-Item -LiteralPath $source -Destination $destination -Force
  }
}

# 1. Remove user-facing Full CMS routes/components/APIs.
$removeTargets = @(
  "app/admin/(dashboard)/cms",
  "components/admin/cms",
  "app/api/admin/cms"
)

foreach ($target in $removeTargets) {
  if (Test-Path -LiteralPath $target) {
    Remove-Item -LiteralPath $target -Recurse -Force
    Write-Host "[CLASSIC ADMIN] remove $target" -ForegroundColor DarkGray
  }
}

# 2. Remove CMS-specific documentation generated by Phase 2/3/6/seed.
$removeFiles = @(
  "ADMIN_CMS_UI.md",
  "CMS_FOUNDATION.md",
  "CMS_MODULES.md",
  "CMS_SEED_GUIDE.md"
)

foreach ($file in $removeFiles) {
  if (Test-Path -LiteralPath $file) {
    Remove-Item -LiteralPath $file -Force
    Write-Host "[CLASSIC ADMIN] remove $file" -ForegroundColor DarkGray
  }
}

# 3. Remove the CMS Workspace launcher injected into the classic sidebar.
$sidebarPath = Join-Path $repoRoot "components/admin/sidebar.tsx"
$sidebar = [System.IO.File]::ReadAllText($sidebarPath)
$beforeSidebar = $sidebar

# Exact launcher inserted by Phase 6 (works across LF/CRLF and whitespace changes).
$sidebar = [regex]::Replace(
  $sidebar,
  '(?s)\s*<a\s+data-lunar-cms-entry="true"[^>]*>.*?</a>',
  ''
)

# Defensive cleanup for a leftover simple link whose only destination is /admin/cms.
$sidebar = [regex]::Replace(
  $sidebar,
  '(?s)\s*<a\s+[^>]*href="/admin/cms"[^>]*>.*?</a>',
  ''
)

if ($sidebar -ne $beforeSidebar) {
  Write-Utf8NoBom $sidebarPath $sidebar
  Write-Host "[CLASSIC ADMIN] patch  components/admin/sidebar.tsx (hapus CMS Workspace)" -ForegroundColor Green
} else {
  Write-Host "[CLASSIC ADMIN] info   CMS Workspace launcher tidak ditemukan di sidebar; tidak ada yang perlu dihapus." -ForegroundColor Yellow
}

# 4. Remove known seed helper files if they were generated outside /admin/cms.
$seedCandidates = @(
  "components/admin/cms-seed-manager.tsx",
  "components/admin/seed/cms-seed-manager.tsx",
  "app/api/admin/seed/cms/route.ts",
  "app/admin/(dashboard)/seed/cms/page.tsx"
)

foreach ($target in $seedCandidates) {
  if (Test-Path -LiteralPath $target) {
    Remove-Item -LiteralPath $target -Recurse -Force
    Write-Host "[CLASSIC ADMIN] remove $target" -ForegroundColor DarkGray
  }
}

# 5. Do NOT delete Firestore collections automatically.
#    Existing page/settings/navigation records remain as recoverable data.
#    Classic CRUD collections stay untouched:
#    services, projects, team, testimonials, faqs, leads, media ownership.

# 6. Scan for surviving user-facing /admin/cms references.
$cmsRefs = @()
try {
  $cmsRefs = @(& git grep -n '/admin/cms' -- ':!*.ps1' ':!*.patch' 2>$null)
} catch {
  $cmsRefs = @()
}

Write-Host ""
Write-Host "[CLASSIC ADMIN] Full CMS workspace sudah dipensiunkan." -ForegroundColor Green
Write-Host "[CLASSIC ADMIN] Admin kembali memakai modul CRUD khusus: Services / Projects / Team / Testimonials / FAQ." -ForegroundColor Green
Write-Host "[CLASSIC ADMIN] Leads API dan business logic TIDAK dihapus." -ForegroundColor Green
Write-Host "[CLASSIC ADMIN] Data Firestore CMS lama TIDAK dihapus otomatis (aman sebagai backup)." -ForegroundColor Green

if ($cmsRefs.Count -gt 0) {
  Write-Host ""
  Write-Host "[CLASSIC ADMIN] Catatan: masih ada referensi internal /admin/cms di file berikut:" -ForegroundColor Yellow
  $cmsRefs | Select-Object -First 20 | ForEach-Object { Write-Host "  $_" }
  Write-Host "Referensi ini tidak otomatis diubah agar installer tidak merusak kode yang tidak dikenal." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Validasi berikutnya:" -ForegroundColor Cyan
Write-Host "  npm run typecheck"
Write-Host "  npm run build"
Write-Host "  git diff --check"
Write-Host "  git status --short"
Write-Host ""
Write-Host "Backup rollback tersedia di:" -ForegroundColor Cyan
Write-Host "  $backupRoot"
