import type { FAQ } from "@/modules/faqs/faq.types";
import type { Project } from "@/modules/projects/project.types";
import type { ConstructionService } from "@/modules/services/service.types";
import type { TeamMember } from "@/modules/team/team.types";
import type { Testimonial } from "@/modules/testimonials/testimonial.types";

export type PublicOverview = {
  services: ConstructionService[];
  projects: Project[];
  team: TeamMember[];
  testimonials: Testimonial[];
  faqs: FAQ[];
};

export const fallbackOverview: PublicOverview = {
  services: [
    {
      id: "fallback-service-1",
      name: "Konstruksi Bangunan",
      slug: "konstruksi-bangunan",
      shortDescription: "Pembangunan hunian, komersial, dan fasilitas publik dengan kontrol mutu yang terukur.",
      description: "Kami mengelola proses konstruksi dari perencanaan teknis hingga serah terima dengan koordinasi lapangan yang disiplin.",
      coverImage: { url: "/service-structure.svg", publicId: "fallback-service-1" },
      features: [{ title: "Terukur", description: "Jadwal, biaya, dan mutu dipantau secara berkala." }],
      scopes: [{ name: "Struktur" }, { name: "Arsitektur" }, { name: "Finishing" }],
      isFeatured: true,
      isPublished: true,
      order: 1,
    },
    {
      id: "fallback-service-2",
      name: "Renovasi & Interior",
      slug: "renovasi-interior",
      shortDescription: "Transformasi ruang lama menjadi lingkungan yang lebih fungsional, matang, dan relevan.",
      description: "Pendekatan renovasi kami menggabungkan audit kondisi, efisiensi ruang, dan detail interior yang tahan pakai.",
      coverImage: { url: "/service-interior.svg", publicId: "fallback-service-2" },
      features: [{ title: "Presisi", description: "Detail dibangun berdasarkan kebutuhan nyata pengguna." }],
      scopes: [{ name: "Audit kondisi" }, { name: "Interior" }, { name: "MEP" }],
      isFeatured: true,
      isPublished: true,
      order: 2,
    },
    {
      id: "fallback-service-3",
      name: "Manajemen Proyek",
      slug: "manajemen-proyek",
      shortDescription: "Pengendalian proyek berbasis koordinasi, dokumentasi, risiko, dan keputusan yang transparan.",
      description: "Kami membantu pemilik proyek menjaga kualitas eksekusi melalui perencanaan, supervisi, dan pelaporan terstruktur.",
      coverImage: { url: "/service-management.svg", publicId: "fallback-service-3" },
      features: [{ title: "Terkendali", description: "Setiap milestone memiliki indikator yang jelas." }],
      scopes: [{ name: "Scheduling" }, { name: "Supervisi" }, { name: "Pelaporan" }],
      isFeatured: true,
      isPublished: true,
      order: 3,
    },
  ],
  projects: [
    {
      id: "fallback-project-1",
      title: "Residence 08",
      slug: "residence-08",
      serviceId: "fallback-service-1",
      clientName: "Private Client",
      location: "Bandung",
      year: 2026,
      shortDescription: "Hunian urban dengan struktur terbuka, cahaya alami, dan material yang jujur.",
      description: "Project hunian yang menekankan hubungan antara ruang dalam, ventilasi silang, dan ritme fasad.",
      coverImage: { url: "/project-residence.svg", publicId: "fallback-project-1" },
      gallery: [],
      scope: ["Struktur", "Arsitektur", "Finishing"],
      materials: ["Beton", "Baja", "Kayu"],
      duration: "8 bulan",
      status: "COMPLETED",
      isFeatured: true,
      isPublished: true,
      order: 1,
    },
    {
      id: "fallback-project-2",
      title: "Workshop North",
      slug: "workshop-north",
      serviceId: "fallback-service-1",
      location: "Cimahi",
      year: 2025,
      shortDescription: "Bangunan kerja yang efisien dengan bentang lebar dan sirkulasi operasional yang ringkas.",
      description: "Fasilitas produksi yang dirancang untuk fleksibilitas operasi dan kemudahan pemeliharaan.",
      coverImage: { url: "/project-workshop.svg", publicId: "fallback-project-2" },
      gallery: [],
      scope: ["Struktur baja", "Atap", "Utilitas"],
      materials: ["Baja profil", "Metal sheet"],
      duration: "6 bulan",
      status: "COMPLETED",
      isFeatured: true,
      isPublished: true,
      order: 2,
    },
    {
      id: "fallback-project-3",
      title: "Atelier Compact",
      slug: "atelier-compact",
      serviceId: "fallback-service-2",
      location: "Jakarta",
      year: 2026,
      shortDescription: "Renovasi ruang kompak menjadi studio yang terang, modular, dan berkarakter.",
      description: "Reorganisasi interior dengan penyimpanan terintegrasi dan material rendah perawatan.",
      coverImage: { url: "/project-atelier.svg", publicId: "fallback-project-3" },
      gallery: [],
      scope: ["Interior", "Custom furniture", "Lighting"],
      materials: ["Plywood", "Steel", "Terrazzo"],
      duration: "3 bulan",
      status: "COMPLETED",
      isFeatured: true,
      isPublished: true,
      order: 3,
    },
  ],
  team: [
    {
      id: "fallback-team-1",
      name: "Raka Pratama",
      position: "Project Director",
      description: "Mengawal koordinasi teknis, kualitas, dan keputusan strategis setiap project.",
      photo: { url: "/team-raka.svg", publicId: "fallback-team-1" },
      skills: ["Project control", "Construction management"],
      order: 1,
      isActive: true,
    },
    {
      id: "fallback-team-2",
      name: "Nadia Laras",
      position: "Design Lead",
      description: "Menerjemahkan kebutuhan pengguna menjadi ruang yang fungsional dan konsisten.",
      photo: { url: "/team-nadia.svg", publicId: "fallback-team-2" },
      skills: ["Architecture", "Interior detailing"],
      order: 2,
      isActive: true,
    },
    {
      id: "fallback-team-3",
      name: "Dimas Aditya",
      position: "Site Manager",
      description: "Menjaga disiplin lapangan, keselamatan kerja, dan kualitas implementasi.",
      photo: { url: "/team-dimas.svg", publicId: "fallback-team-3" },
      skills: ["Site execution", "Quality assurance"],
      order: 3,
      isActive: true,
    },
  ],
  testimonials: [
    {
      id: "fallback-testimonial-1",
      clientName: "Andreas W.",
      clientPosition: "Pemilik Residence 08",
      projectName: "Residence 08",
      message: "Tim bekerja terstruktur, komunikasinya jelas, dan setiap perubahan dijelaskan bersama dampak biaya serta waktunya.",
      rating: 5,
      isPublished: true,
      order: 1,
    },
    {
      id: "fallback-testimonial-2",
      clientName: "Mira S.",
      clientPosition: "Operations Director",
      projectName: "Workshop North",
      message: "Eksekusi lapangan rapi dan dokumentasinya membantu kami mengambil keputusan tanpa menebak-nebak kondisi proyek.",
      rating: 5,
      isPublished: true,
      order: 2,
    },
  ],
  faqs: [
    {
      id: "fallback-faq-1",
      question: "Apakah Lunar Konstruksi melayani desain sekaligus pembangunan?",
      answer: "Ya. Skema pekerjaan dapat mencakup desain, pengembangan gambar kerja, estimasi, pelaksanaan konstruksi, hingga pengawasan dan serah terima.",
      order: 1,
      isPublished: true,
    },
    {
      id: "fallback-faq-2",
      question: "Bagaimana proses awal sebelum proyek dimulai?",
      answer: "Kami memulai dengan konsultasi kebutuhan, survei lokasi, penentuan ruang lingkup, estimasi awal, dan penyusunan tahapan kerja yang dapat dievaluasi bersama.",
      order: 2,
      isPublished: true,
    },
    {
      id: "fallback-faq-3",
      question: "Apakah progres proyek dilaporkan secara berkala?",
      answer: "Ya. Laporan dapat mencakup progres fisik, dokumentasi lapangan, isu teknis, keputusan yang dibutuhkan, serta evaluasi jadwal dan biaya.",
      order: 3,
      isPublished: true,
    },
  ],
};
